# Copyright (c) IncQuery Labs cPlc.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: IncQuery Validator for Enterprise Architect
description: This action downloads and installs the IncQuery Validator for Enterprise Architect, then runs a validation on the given model with the given ruleset.

inputs:
  model_file_path:
    description: "Path to the model file."
    required: true
  analysis_suite:
    description: "Name of the analysis suite (ruleset) to validate with."
    required: true
  incquery_username:
    description: "Username to https://artifacts.incquery.io/. Not required if the validator is already installed on the runner."
    required: false
  incquery_password:
    description: "Password to https://artifacts.incquery.io/. Not required if the validator is already installed on the runner."
    required: false
  license:
    description: "The contents of the supplied license file."
    required: true

runs:
  using: "composite"
  steps:
    - name: Download and install IncQuery Validator for Enterprise Architect
      shell: pwsh
      run: |
        if (Test-Path -Path 'C:/Program Files/IncQuery Labs/IncQuery Validator for Enterprise Architect/CI/run_validation.ps1' -PathType Leaf )
        {
          echo "IncQuery Validator for Enterprise Architect is already installed."
        }
        else
        {
          $setupWebUrl = "https://artifacts.incquery.io/incquery-suite/incquery-validator-for-ea/IncQuery%20Validator%20for%20Enterprise%20Architect%202023.1.2%20Setup.exe"
          $user = "${{ inputs.incquery_username }}"
          $pass= "${{ inputs.incquery_password }}"
          if ( $user.Length -eq 0 ) { exit 1 }
          if ( $pass.Length -eq 0 ) { exit 1 }
          $secpasswd = ConvertTo-SecureString $pass -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($user, $secpasswd)
          Invoke-WebRequest $setupWebUrl -Credential $credential -OutFile "${{ runner.temp }}/IncQuery Validator for Enterprise Architect Setup.exe"
          Start-Process -FilePath '${{ runner.temp }}/IncQuery Validator for Enterprise Architect Setup.exe' -ArgumentList @("/install", "/quiet") -Wait
        }
    - name: Create the license file
      shell: pwsh
      run: |
        echo '${{ inputs.license }}' | Out-File -FilePath '${{ runner.temp }}/IncQueryValidatorLicense.lic'

    - name: Run validation
      shell: pwsh
      run: |
        & 'C:\Program Files\IncQuery Labs\IncQuery Validator for Enterprise Architect\CI\run_validation.ps1' -model '${{ inputs.model_file_path }}' -licenseFile '${{ runner.temp }}/IncQueryValidatorLicense.lic' -outputPath '${{ runner.temp }}/validation_result' -analysisSuite '${{ inputs.analysis_suite }}'

    - name: "Archive analysis result"
      uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.analysis_suite }} analysis result"
        path: ${{ runner.temp }}/validation_result/

branding:
  icon: 'box'
  color: 'blue'